# Generated by Django 5.1.6 on 2025-03-01 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
