# Generated by Django 4.1.7 on 2025-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0002_remove_product_id_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
