# Generated by Django 4.1.7 on 2025-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0003_product_isnew_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
