# Generated by Django 4.1.7 on 2025-05-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seniority', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
            ],
        ),
    ]
