# Generated by Django 4.1.7 on 2025-05-04 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserJobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='technology',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
